### ISSUE TITLE
plans unclear

### ISSUE THREAD

**Issue by i-make-robots** [vhs/multicopters#3]
There are pieces nested within the top and bottom panels.  Should they also be 1/8" thick?
It might be helpful to split the DXF in two: one for 1/8" pieces and one for 1/4".  name the files accordingly, please.

**Comment by garthomite** [comment]
Yes 1/8" thick for these parts. If I get time to make the change i'll do that otherwise fell free create a pull request.

**Comment by i-make-robots** [comment]
I'm on it.

On Wed, Mar 11, 2015 at 1:26 PM, Garth Cumming <notifications@github.com>
wrote:

> Yes 1/8" thick for these parts. If I get time to make the change i'll do
> that otherwise fell free create a pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vhs/multicopters/issues/3#issuecomment-78363487>.
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by i-make-robots** [comment]
Committed.  Have I done it right?  Did I put the right filename on each part?

**Comment by garthomite** [comment]
Yup, looks good. 

Thanks!
